### ISSUE TITLE
:open cmd no longer works

### ISSUE THREAD

**Issue by joemewes** [4AllDigital/DruDockCli#124]
think this needs a review and cross OS support/tests

**Comment by aleach** [comment]
On build:init, the last step opens the project url. If firefox is not installed the following error occurs:
0:45: execution error: "http://example.local:32786" doesn’t understand the “open location” message. (-1708) 70:78: execution error: Can’t get application "firefox". (-1728)

Drudock should have a class the handles opening urls in a browser window, which should have oversight of the default system browser. This class and methods can then be used across the project [eg. drush:uli].

However, this currently successfully opens the url in 'safari', but this is not the current default browser.

**Comment by joemewes** [comment]
seems to working fine now, and believe this may have been a bug in MacOS.

test : `python -mwebbrowser http://google.com`
