### ISSUE TITLE
Make it easier to ssh to a docker instance

### ISSUE THREAD

**Issue by aleach** [4AllDigital/DruDockCli#131]
Command: drudock ssh
This would list all available boxes with running ssh (cross-project). Selecting a number would ssh into the box.
If we are in a application directory it would show the available boxes for the current project running ssh.
If there is only one box with ssh running it would automagically ssh into this box.

**Comment by joemewes** [comment]
need ro resolve these :
```
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_dsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Disabling protocol version 2. Could not load host ke
```

`/usr/bin/ssh-keygen -A` will help

**Comment by joemewes** [comment]
and adding authorised_keys file to project? docker-compose.yml ?

eg. - './config/php/authorized_keys:/root/.ssh/authorized_keys'

**Comment by joemewes** [comment]
completed. first pass add `app:ssh` command functional. :: https://github.com/4AllDigital/DruDockCli/commit/eaae10901f94b22f7743d38f3e8f74a1b77568c2
