### ISSUE TITLE
Support of Home directory alias

### ISSUE THREAD

**Issue by aleach** [4AllDigital/DruDockCli#132]
The usage of the home directory alias '~' should be allowed in all commands.
mysql:import does not currently support this alias, there may also be other commands that this is not supported by. User input should be passed through a method to 'clean' the input and this may be used to replace certain aliases and environment variables.

**Comment by joemewes** [comment]
`mysql:import -p ~/dev/__playground__/d8newpp_development/test.sql` works fine.

more info or ability to reproduce required.
