### ISSUE TITLE
Drush:uli should open the path in a new browser window

### ISSUE THREAD

**Issue by aleach** [4AllDigital/DruDockCli#133]
It would be good for the uli option to follow the same standard as the core drush uli option. Defaulting to opening the one time login link in the users default browser.
It would also be good to have the parameters for these drush commands passed over. Allowing a different user and allowing to disable the auto opening of the browser.

**Comment by joemewes** [comment]
resolve, but still using `python -mwebbrowser ` like default `app:open` command.
