### ISSUE TITLE
Use default browser to open links

### ISSUE THREAD

**Issue by aleach** [4AllDigital/DruDockCli#140]
On build:init, the last step opens the project url. If firefox is not installed the following error occurs:
`0:45: execution error: "http://example.local:32786" doesn’t understand the “open location” message. (-1708)
70:78: execution error: Can’t get application "firefox". (-1728)`

Drudock should have a class the handles opening urls in a browser window, which should have oversight of the default system browser. This class and methods can then be used across the project [eg. drush:uli]

**Comment by joemewes** [comment]
duplicate : https://github.com/4AllDigital/DruDockCli/issues/124

**Comment by aleach** [comment]
However, this currently successfully opens the url in 'safari', but this is not the current default browser.
