### ISSUE TITLE
drudock start on already running app fails

### ISSUE THREAD

**Issue by aleach** [4AllDigital/DruDockCli#141]
When the app is already running, drudock start fails with the following error:

You have other containers running. Would you like to stop them? [y/n] : n
 [WARNING] APP has no containers, try running `drudock build:init --help`                                                                             
 [WARNING] APP has no containers, try running `drudock build:init --help`

**Comment by aleach** [comment]
Also, other commands do not have overview that it is running.

PHP ::: drush uli
-----------------                                                    
 [WARNING] APP has no containers, try running `drudock build:init --help`

**Comment by aleach** [comment]
Forcing the app's containers to stop using `docker stop [container]` and then running `drudock start` solves this.

**Comment by joemewes** [comment]
```
You have running containers for your current App.
-------------------------------------------------

Try one of the following is you are experiencing issues ::

[drudock docker:stop]

[drudock docker:restart]

[drudock up:ct]

```
Is current response for running APP .
