### ISSUE TITLE
Add SSH feature

### ISSUE THREAD

**Issue by jnpwebdeveloper** [4AllDigital/DruDockCli#169]
Would be nice to have each drudock service provide an SSH command so you can SSH directly onto that container. E.g.:

drudock nginx:ssh
drudock redis:ssh
drudock mysql:ssh

Etc. Would allow us to quickly jump onto a container without having to docker ps + docker exec -it id bash.

**Comment by joemewes** [comment]
I think SSH is inly really valuable on PHP container as it adds potential to intagrate with drush @alias commands.

That said , a quick way to get "into" container is useful, so I'll add a shorthand `:bash` command.

**Comment by jnpwebdeveloper** [comment]
Awesome. Yes, think PHP container would suffice. Would be a nice little addition.

**Comment by joemewes** [comment]
FYI - SSH command is done and will be included in next release :: https://github.com/4AllDigital/DruDockCli/commit/eaae10901f94b22f7743d38f3e8f74a1b77568c2

**Comment by jnpwebdeveloper** [comment]
Ah mate - you already done that. Awesome :)
