### ISSUE TITLE
guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by mediaashley** [4AllDigital/DruDockCli#185]
"Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

**Comment by joemewes** [comment]
@mediaashley where are you seeing this required?

**Comment by mediaashley** [comment]
I think I cloned the repo, and let Phpstorm do it's thing. I don't recall where it was required.

**Comment by mediaashley** [comment]
Strangely, the only mention I see is in the change log for guzzle and guzzlehttp, but I don't see where guzzle/guzzle is required.

When I do a composer install I get the warning.

**Comment by mediaashley** [comment]
It looks like it's a requirement of alchemy/zippy
