### ISSUE TITLE
Add aliases to readme / list comand

### ISSUE THREAD

**Issue by mediaashley** [4AllDigital/DruDockCli#186]
Looking in`DrushClearCacheCommand` etc. I see that each command has an alias, it would be good to list these somewhere like the readme, or when running `drudock list`.

**Comment by joemewes** [comment]
`drudock list` output should show commands with alias'

eg. `app:bash               [ab] Bash into container`

[ab] is the alias

**Comment by joemewes** [comment]
also in the README https://github.com/4AllDigital/DruDockCli#initial-commands-structure

**Comment by mediaashley** [comment]
👀 Totally never noticed that…

Soz.
