### ISSUE TITLE
D8 specific commands

### ISSUE THREAD

**Issue by joemewes** [4AllDigital/DruDockCli#45]
add drush config; import/export

with --partial and sync options

**Comment by mediaashley** [comment]
+1 for this! It's a reallly common requirement on D8. I think I use it and CR the most.

Just now you can achive this with ` drudock app:exec -c "drush cex -y"` and select PHP from the list of service/containers.

Even a basic `cex` and `cim` would be realy helpful.

Have you considered something like `drudock drush:exce "drush command"`?

**Comment by joemewes** [comment]
@mediaashley PR merged. will close issue for now. can re-open if further dev required.
